server:
  host: 0.0.0.0
  port: 8081
  debug: true
  server_id: 524aa2f0-72e8-42bb-acb2-42b025942727
  server_name: mall4micro-product
  server_tags:
    - product
  address: 192.168.0.115
  service_check:
    deregister_critical_service_after: 90s
    args:
      - curl
      - http://192.168.0.115:8081/api/product/ping
    interval: 10s
    timeout: 2s
  service_weights:
    passing: 10
    warning: 1

mysql:
  host: 0.0.0.0
  port: 3306
  user: root
  password: 123456
  database: mall4micro-product
  max_idle_conn: 900
  max_conn: 1000